language: python

python: "3.6"

# don't clone more than necessary
git:
  depth: 1

# Install dependencies
install:
  - pip install -r requirements.txt

env:
- CODECOV_TOKEN='160ac283-4e59-46cb-bdfa-100a9b3e782f'
  global:
  - secure: # encrypted string for SECRET_KEY
  - secure: # encrypted string for another settings KEY
  
# script to run tests. Script can have many commands, one per line.
script: 
  - python manage.py test
  - coverage run manage.py test

after_script:
  - bash <(curl -s https://codecov.io/bash)
  